### PR TITLE
New request notifications: Repository issue and email to user

### PR DESCRIPTION
**Pull request by achilleas-k**
This PR makes several major changes to the new request notification system:
- On successful submission of a DOI request, an email is sent to the requesting user with a similar message to the one found on the success page.  I think this is close to what users may expect and it also gives users access to the info on the success page (DOI, wait time, etc) after they have closed the tab.
- In addition to emailing admins that a new request has been received, the service opens an issue on a configured GIN repository with the same content.  This can be used to comment on issues with the registration procedure outside of email where things can get messy.
     - The issue content includes the entire XML file content.
- Any followup email and issue after the first one wont include the full info of the request.

Additional changes:
- On successful submission of a DOI request, the user was told that it might take several hours to finalise.  This has changed to "up to two work days", to manage expectations for more busy periods when we might be slower with publishing.
- Updates the footer to match GIN Web.
- Includes code that checks if a repository has already been published in order to automatically add the "IsNewVersionOf" related identifier to the doi.xml.  However, the API endpoint for listing tags/releases isn't available in GIN Web yet (though it exists in upstream GOGS), so until we update GIN, this wont work.  A warning will be included in the notification email and issue that the repository has a fork under the DOI service user to make sure we check for existing releases.

### CODE REVIEW

**Comment by achilleas-k** [comment]
One more change: Repository links (buttons) are not rendered on the landing page when they're not specified.  For example when a source repository is deleted (and removed from the XML), this will now remove the button from the landing page as well.

**Comment by achilleas-k** [comment]
Found a bug in the issue creation logic.  Marking as draft until it's fixed.

**Comment by achilleas-k** [comment]
TODO: Add a notice to the final request page that an email has been sent with the information.

**Comment by achilleas-k** [comment]
All ready now (from my side).

**Review by mpsonntag — APPROVED** [review]
LGTM

**Pull request merged**
